### ISSUE TITLE
Search function broken - asking to activate Javascript?

### ISSUE THREAD

**Issue by TomNicholas** [data-apis/data-apis.github.io#24] opened 2024-02-09 18:22 UTC
Hi,

This is happening when I try to search on the website (e.g. https://data-apis.org/array-api/2022.12/search.html?q=broadcast_like#)

<img width="978" alt="Screenshot 2024-02-09 at 1 21 41 PM" src="https://github.com/data-apis/data-apis.github.io/assets/35968931/330e83d9-7f5b-4aa9-a36f-59fcceec3380">

I don't think this is my fault - I've definitely got javascript enabled, and besides I also tried this on mobile and saw the same error.

**Comment by kgryte** [comment] 2024-02-10 07:51
Hmm...odd. Search is working. For example, if you search `sine` (https://data-apis.org/array-api/2022.12/search.html?q=sine), you get search results. 

Not sure why the banner is appearing. We recently updated Sphinx, so this may have something to do with it.

**Comment by rgommers** [comment] 2024-02-10 12:49
Thanks for reporting this @TomNicholas. This is https://github.com/bashtage/sphinx-material/issues/132. Looks like Sphinx 5.x is unaffected, while with 6.x this is visible in the search pages of the non-default versions of the docs.

Search indeed still works, so it's simply a spurious warning. 

We had to upgrade Sphinx in https://github.com/data-apis/array-api/pull/735. I'll see if there's an in-between version that we can use for now. Hopefully the theme bug gets fixed in the near future.

**Comment by rgommers** [comment] 2024-02-10 13:05
Hmm, going back to Sphinx 5.3.0 makes other build warnings re-appear, I think there's no good workaround here other than get the `sphinx-material` theme fixed.

**Comment by rgommers** [comment] 2024-03-05 16:05
This has been fixed by https://github.com/data-apis/array-api/pull/758. The root cause was that Sphinx 5 stopped shipping jQuery. Installing it with `sphinxcontrib-jquery` restored the old behavior.

Thanks @TomNicholas and @kgryte

**Closed as completed by rgommers** 2024-03-05 16:05 UTC
